name: Terraform Plan - Client Secret

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform/Terraform Module_10.07.2026/Terraform-Parent-Child-Module-10thJul2026/parent

    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Azure Login using Client Secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # 3. Verify Azure account
      - name: Verify Azure Account
        run: |
          az account show --query "{Subscription:id, Tenant:tenantId, Name:name}" -o table

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.7

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
