name: Terraform Production Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  # ============================================================
  # 1. SECURITY SCAN
  # ============================================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------------- Gitleaks ----------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- TFLint ----------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        working-directory: ./parent
        run: |
          tflint --init
          tflint

      # ---------------- tfsec ----------------
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_dir: ./parent